export const weatherConditions = {
	clear: [ 'clear', 'ясно', 'ясна' ],
	cloudy: [ 'cloudy', 'облачно', 'воблачна' ],
	drizzle: [ 'drizzle', 'изморось', 'імжа' ],
	flurries: [ 'flurries', 'порывы', 'шквал' ],
	fog: [ 'fog', 'туман', 'туман' ],
	fog_light: [ 'fog light', 'легкий туман', 'лёгкі туман' ],
	freezing_drizzle: [ 'freezing drizzle', 'ледяной дождь', 'ледзяны дождж' ],
	freezing_rain: [ 'freezing rain', 'ледяной дождь', 'ледзяны дождж' ],
	freezing_rain_heavy: [ 'freezing rain heavy', 'сильный ледяной дождь', 'моцны ледзяны дождж' ],
	freezing_rain_light: [ 'freezing rain light', 'слабый ледяной дождь', 'слабы ледзяны дождж' ],
	ice_pellets: [ 'ice pellets', 'ледяной град', 'ледзяной град' ],
	ice_pellets_heavy: [ 'ice pellets heavy', 'сильный ледяной град', 'моцны ледзяной град' ],
	ice_pellets_light: [ 'ice pellets light', 'слабый ледяной град', 'слабы ледзяной град' ],
	mostly_clear: [ 'mostly clear', 'в большей степени ясно', 'у асноўным ясна' ],
	mostly_cloudy: [ 'mostly cloudy', 'в основном облачно', 'пераважна воблачна' ],
	partly_cloudy: [ 'partly cloudy', 'переменная облачность', 'пераменная воблачнасць' ],
	rain: [ 'rain', 'дождь', 'дождж' ],
	rain_heavy: [ 'rain heavy', 'сильный дождь', 'моцны дождж' ],
	rain_light: [ 'rain light', 'слабый дождь', 'слабы дождж' ],
	snow: [ 'snow', 'снег', 'снег' ],
	snow_heavy: [ 'snow heavy', 'снегопад', 'снегапад' ],
	snow_light: [ 'snow light', 'слабый снег', 'слабы снег' ],
	tstorm: [ 'storm', 'гроза', 'навальніца' ]
};
