export const weatherConditions = {
	clear: [ 'clear', 'ясно', 'ясна', 'jasny' ],
	cloudy: [ 'cloudy', 'облачно', 'воблачна', 'pochmurny' ],
	drizzle: [ 'drizzle', 'изморось', 'імжа', 'mżawka' ],
	flurries: [ 'flurries', 'порывы', 'шквал', 'mroczne' ],
	fog: [ 'fog', 'туман', 'туман', 'mgła' ],
	fog_light: [ 'fog light', 'легкий туман', 'лёгкі туман', 'światła przeciwmgielne' ],
	freezing_drizzle: [ 'freezing drizzle', 'ледяной дождь', 'ледзяны дождж', 'marznąca mżawka' ],
	freezing_rain: [ 'freezing rain', 'ледяной дождь', 'ледзяны дождж', 'marznący deszcz' ],
	freezing_rain_heavy: [ 'freezing rain heavy', 'сильный ледяной дождь', 'моцны ледзяны дождж', 'marznący deszcz' ],
	freezing_rain_light: [ 'freezing rain light', 'слабый ледяной дождь', 'слабы ледзяны дождж', 'marznące światło deszczu' ],
	ice_pellets: [ 'ice pellets', 'ледяной град', 'ледзяной град', 'granulki lodu' ],
	ice_pellets_heavy: [ 'ice pellets heavy', 'сильный ледяной град', 'моцны ледзяной град', 'granulki lodu ciężkie' ],
	ice_pellets_light: [ 'ice pellets light', 'слабый ледяной град', 'слабы ледзяной град', 'lekkie granulki lodu' ],
	mostly_clear: [ 'mostly clear', 'в большей степени ясно', 'у асноўным ясна', 'w większości jasne' ],
	mostly_cloudy: [ 'mostly cloudy', 'в основном облачно', 'пераважна воблачна', 'przeważnie pochmurno' ],
	partly_cloudy: [ 'partly cloudy', 'переменная облачность', 'пераменная воблачнасць', 'częściowe zachmurzenie' ],
	rain: [ 'rain', 'дождь', 'дождж', 'deszcz' ],
	rain_heavy: [ 'rain heavy', 'сильный дождь', 'моцны дождж', 'ulewny deszcz' ],
	rain_light: [ 'rain light', 'слабый дождь', 'слабы дождж', 'światło deszczu' ],
	snow: [ 'snow', 'снег', 'снег', 'śnieg' ],
	snow_heavy: [ 'snow heavy', 'снегопад', 'снегапад', 'śnieg ciężki' ],
	snow_light: [ 'snow light', 'слабый снег', 'слабы снег', 'lekki śnieg' ],
	tstorm: [ 'storm', 'гроза', 'навальніца', 'burza' ]
};
